services:
  locker-app:
    image: 'ghcr.io/open-locker/locker-backend:latest'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    env_file:
      - .env.prod
    environment:
      WWWUSER: '1000'
    volumes:
      - storage_data:/var/www/html/storage
    networks:
      - open-locker

  locker-worker:
    image: 'ghcr.io/open-locker/locker-backend:latest'
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      WWWUSER: '1000'
    command: php artisan queue:work --tries=3 --timeout=90 --sleep=3 --max-jobs=1000
    volumes:
      - storage_data:/var/www/html/storage
    networks:
      - open-locker
    depends_on:
      - locker-app

  locker-poller:
    image: 'ghcr.io/open-locker/locker-backend:latest'
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      WWWUSER: '1000'
    command: php artisan locker:poll-status --verbose
    volumes:
      - storage_data:/var/www/html/storage
    networks:
      - open-locker
    depends_on:
     - locker-app

networks:
  open-locker:
    driver: bridge

volumes:
  storage_data:
    driver: local
