export {
  OPEN_LOCKER_DARK_BACKGROUND,
  OPEN_LOCKER_DARK_OUTLINE,
  OPEN_LOCKER_DARK_SURFACE,
  OPEN_LOCKER_DARK_SURFACE_VARIANT,
  OPEN_LOCKER_DESIGN_TOKENS,
  OPEN_LOCKER_LIGHT_BACKGROUND,
  OPEN_LOCKER_LIGHT_OUTLINE,
  OPEN_LOCKER_LIGHT_SURFACE,
  OPEN_LOCKER_LIGHT_SURFACE_VARIANT,
  OPEN_LOCKER_PRIMARY,
  OPEN_LOCKER_PRIMARY_HEX,
} from '@/src/theme/tokens';
