[platformio]
src_dir = main

[env:wemos_d1_mini32]
platform = espressif32@7.1.3
board = wemos_d1_mini32
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
extra_scripts = pre:scripts/bootloader_link_path.py
build_flags = -Wall -Wextra -Werror -DCJSON_NESTING_LIMIT=16
