#!/usr/bin/env bash
# Paired with setup-mqtt.ps1. Keep input precedence, generated bytes, messages,
# mutation order, and exit behavior equivalent. Never print the password.
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="$root_dir/locker-backend/.env"
template="$root_dir/locker-backend/mosquitto/mosquitto.conf.template"
target="$root_dir/locker-backend/mosquitto/mosquitto.conf"

if [[ ! -f "$env_file" ]]; then
    echo "Error: backend environment file not found: $env_file" >&2
    exit 1
fi

if [[ ! -f "$template" ]]; then
    echo "Error: Mosquitto template not found: $template" >&2
    exit 1
fi

password="${MOSQ_HTTP_PASS:-}"
if [[ -z "$password" ]]; then
    while IFS='=' read -r key value; do
        if [[ "$key" == "MOSQ_HTTP_PASS" ]]; then
            password="${value%$'\r'}"
            break
        fi
    done < "$env_file"
fi

if [[ "$password" == \"*\" && "$password" == *\" ]]; then
    password="${password:1:${#password}-2}"
elif [[ "$password" == \'*\' && "$password" == *\' ]]; then
    password="${password:1:${#password}-2}"
fi

if [[ -z "$password" ]]; then
    echo "Error: MOSQ_HTTP_PASS is missing from the environment and $env_file" >&2
    exit 1
fi

escaped_password="${password//\\/\\\\}"
escaped_password="${escaped_password//&/\\&}"
escaped_password="${escaped_password//|/\\|}"

umask 077
temporary="$target.tmp.$$"
trap 'rm -f "$temporary"' EXIT
sed "s|__AUTH_PASS__|$escaped_password|g" "$template" > "$temporary"
mv "$temporary" "$target"
trap - EXIT

echo "Mosquitto configuration generated at $target"
docker compose -f "$root_dir/locker-backend/docker-compose.yml" restart mqtt
