# Paired with setup-mqtt.sh. Keep input precedence, generated bytes, messages,
# mutation order, and exit behavior equivalent. Never print the password.
# Remain compatible with stock Windows PowerShell 5.1 and check native exit codes.
$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $root 'locker-backend/.env'
$template = Join-Path $root 'locker-backend/mosquitto/mosquitto.conf.template'
$target = Join-Path $root 'locker-backend/mosquitto/mosquitto.conf'

if (-not (Test-Path -LiteralPath $envFile -PathType Leaf)) {
    throw "Backend environment file not found: $envFile"
}

if (-not (Test-Path -LiteralPath $template -PathType Leaf)) {
    throw "Mosquitto template not found: $template"
}

$password = $env:MOSQ_HTTP_PASS
if ([string]::IsNullOrEmpty($password)) {
    $line = Get-Content -LiteralPath $envFile |
        Where-Object { $_ -match '^MOSQ_HTTP_PASS=' } |
        Select-Object -First 1

    if ($line -match '^MOSQ_HTTP_PASS=(.*)$') {
        $password = $Matches[1]
    }
}

if ($password -match '^(".*"|''.*'')$') {
    $password = $password.Substring(1, $password.Length - 2)
}

if ([string]::IsNullOrEmpty($password)) {
    throw "MOSQ_HTTP_PASS is missing from the environment and $envFile"
}

$temporary = "$target.tmp.$PID"
try {
    $content = (Get-Content -LiteralPath $template -Raw).Replace('__AUTH_PASS__', $password)
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($temporary, $content, $utf8NoBom)
    Move-Item -LiteralPath $temporary -Destination $target -Force
} finally {
    if (Test-Path -LiteralPath $temporary) {
        Remove-Item -LiteralPath $temporary -Force
    }
}

Write-Output "Mosquitto configuration generated at $target"
docker compose -f (Join-Path $root 'locker-backend/docker-compose.yml') restart mqtt
if ($LASTEXITCODE -ne 0) {
    throw "docker compose restart mqtt failed with code $LASTEXITCODE"
}
